# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('licitacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='publicada',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
