# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacion', '0002_licitacion_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='publicada',
            field=models.CharField(max_length=40),
        ),
    ]
