# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacion', '0004_auto_20180623_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='publicada',
            field=models.BooleanField(auto_created=True),
        ),
    ]
