# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0002_auto_20180622_1030'),
        ('licitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('adjunto', models.FileField(upload_to='media')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrato.Contrato')),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacion.Licitacion')),
            ],
        ),
    ]
