# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='checkbox',
            field=models.BooleanField(default=True),
        ),
    ]
