# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_auto_20180623_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='adjunto',
            field=models.FileField(default=True, upload_to='media/'),
        ),
    ]
