# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='licitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacion.Licitacion'),
        ),
    ]
